name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NODE_OPTIONS: "--max-old-space-size=32768"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js, 1 linux-extra-large-js" --with-env-vars="NODE_OPTIONS"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx run-many -t typecheck build --parallel 2
